#ifndef _PIXELS_CONFIG_HPP

#define DEFAULT_PRICE 10000
#define FEE_PERCENTAGE 25

#define PRICE_MULTIPLIER 1.5
#define CANVAS_DURATION 60 * 20
#define CANVAS_ADD_DURATION 1
#define MAX_COORDINATE_X_PLUS_ONE 300
#define MAX_COORDINATE_Y_PLUS_ONE 300
#define PIXELS_PER_ROW 50

#define PATRON_BONUS_PERCENTAGE_POINTS 40
#define POT_PERCENTAGE_POINTS 42

// number of pixels sold anything may be withdrawn
#define WITHDRAW_PIXELS_THRESHOLD 50

#define REFERRER_PERCENTAGE_POINTS 8
// TEAM_PERCENTAGE == 10
#define PRECISION_BASE 1e16
#define TEAM_ACCOUNT N(ceoimondev11)

#define WITHDRAW_QUOTA 10000000000  // 1000000 EOS

#endif
